/*
 * This file is generated by jOOQ.
 */
package com.cta4j.jooq;


import com.cta4j.jooq.tables.Station;


/**
 * Convenience access to all tables in cta4j.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>cta4j.station</code>.
     */
    public static final Station STATION = Station.STATION;
}
